import { ReportRow, Company, Trend, GeneratedReport } from "./types";

export const mockReports: ReportRow[] = [
  {
    slug: "french-fintech",
    industry: "French Fintech",
    type: "Full Analysis",
    status: "Active",
    region: "France",
    execBrief: "Strong VC activity, BNP/SG incumbents under pressure",
    geoFocus: "Paris, Lyon",
    keyPlayer: "Qonto",
    estFunding: "€2.1B",
    signal: "up",
  },
  {
    slug: "ai-healthcare",
    industry: "AI in Healthcare",
    type: "Deep Dive",
    status: "Active",
    region: "Europe",
    execBrief: "Regulatory tailwinds, NHS + AP-HP partnerships",
    geoFocus: "UK, France, Germany",
    keyPlayer: "Owkin",
    estFunding: "€890M",
    signal: "up",
  },
  {
    slug: "climate-tech",
    industry: "European Climate Tech",
    type: "Quick Brief",
    status: "Active",
    region: "Europe",
    execBrief: "Green Deal funding accelerating, hardware still challenged",
    geoFocus: "Germany, Nordics",
    keyPlayer: "Northvolt",
    estFunding: "€4.3B",
    signal: "stable",
  },
  {
    slug: "b2b-saas",
    industry: "B2B SaaS",
    type: "Full Analysis",
    status: "Draft",
    region: "Global",
    execBrief: "AI feature race, consolidation wave incoming",
    geoFocus: "USA, Europe",
    keyPlayer: "Notion",
    estFunding: "€12B",
    signal: "up",
  },
  {
    slug: "mobility",
    industry: "Urban Mobility",
    type: "Quick Brief",
    status: "Archived",
    region: "Europe",
    execBrief: "Post-COVID recovery, micromobility regulation tightening",
    geoFocus: "Paris, Berlin",
    keyPlayer: "Lime",
    estFunding: "€1.2B",
    signal: "down",
  },
  {
    slug: "deep-tech",
    industry: "Deep Tech",
    type: "Full Analysis",
    status: "Active",
    region: "Europe",
    execBrief: "Quantum and photonics garnering sovereign fund interest",
    geoFocus: "France, UK, Netherlands",
    keyPlayer: "Pasqal",
    estFunding: "€650M",
    signal: "up",
  },
  {
    slug: "edtech",
    industry: "EdTech",
    type: "Quick Brief",
    status: "Draft",
    region: "Europe",
    execBrief: "AI tutoring adoption accelerating post-ChatGPT era",
    geoFocus: "UK, France",
    keyPlayer: "Didask",
    estFunding: "€210M",
    signal: "stable",
  },
  {
    slug: "cybersecurity",
    industry: "Cybersecurity",
    type: "Deep Dive",
    status: "Active",
    region: "Global",
    execBrief: "Nation-state threat surge driving enterprise spend",
    geoFocus: "Israel, USA, France",
    keyPlayer: "Wiz",
    estFunding: "€5.8B",
    signal: "up",
  },
];

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Qonto",
    industry: "French Fintech",
    type: "Scale-up",
    stage: "Series C+",
    hq: "Paris, France",
    funding: "€622M",
    founded: 2017,
    description: "Business banking platform for SMEs and freelancers across Europe.",
    notable: "5M+ customers, profitable since 2023",
  },
  {
    id: "2",
    name: "Owkin",
    industry: "AI in Healthcare",
    type: "Scale-up",
    stage: "Series B",
    hq: "Paris, France",
    funding: "€270M",
    founded: 2016,
    description: "Federated learning platform for drug discovery and clinical trials.",
    notable: "Partnership with Sanofi worth $180M",
  },
  {
    id: "3",
    name: "Northvolt",
    industry: "European Climate Tech",
    type: "Scale-up",
    stage: "Series C+",
    hq: "Stockholm, Sweden",
    funding: "€9.2B",
    founded: 2016,
    description: "European battery cell manufacturer targeting EV and energy storage markets.",
    notable: "BMW, Volkswagen as anchor customers",
  },
  {
    id: "4",
    name: "Pasqal",
    industry: "Deep Tech",
    type: "Startup",
    stage: "Series B",
    hq: "Massy, France",
    funding: "€140M",
    founded: 2019,
    description: "Neutral atom quantum computing startup with real-world optimization use cases.",
    notable: "First quantum company funded by French sovereign fund",
  },
  {
    id: "5",
    name: "Wiz",
    industry: "Cybersecurity",
    type: "Scale-up",
    stage: "Series C+",
    hq: "New York, USA",
    funding: "€1.9B",
    founded: 2020,
    description: "Cloud security platform with agentless scanning across multi-cloud environments.",
    notable: "Reached $100M ARR in 18 months — fastest ever in SaaS",
  },
  {
    id: "6",
    name: "Lime",
    industry: "Urban Mobility",
    type: "Scale-up",
    stage: "Series C+",
    hq: "San Francisco, USA",
    funding: "€1.1B",
    founded: 2017,
    description: "Electric scooter and bike-sharing operator in 250+ cities globally.",
    notable: "Profitability achieved in 2022 despite regulatory headwinds",
  },
  {
    id: "7",
    name: "Notion",
    industry: "B2B SaaS",
    type: "Scale-up",
    stage: "Series C+",
    hq: "San Francisco, USA",
    funding: "€330M",
    founded: 2016,
    description: "All-in-one workspace combining notes, docs, databases and project management.",
    notable: "$10B valuation, 30M+ users globally",
  },
  {
    id: "8",
    name: "Alan",
    industry: "French Fintech",
    type: "Scale-up",
    stage: "Series C+",
    hq: "Paris, France",
    funding: "€490M",
    founded: 2016,
    description: "Digital health insurance company disrupting traditional mutual insurance model.",
    notable: "600K members, expanding into Spain and Belgium",
  },
  {
    id: "9",
    name: "Didask",
    industry: "EdTech",
    type: "Startup",
    stage: "Series A",
    hq: "Paris, France",
    funding: "€12M",
    founded: 2016,
    description: "Cognitive science–based corporate e-learning platform powered by AI.",
    notable: "CAC40 companies as enterprise clients",
  },
  {
    id: "10",
    name: "Pigment",
    industry: "B2B SaaS",
    type: "Scale-up",
    stage: "Series B",
    hq: "Paris, France",
    funding: "€220M",
    founded: 2019,
    description: "Business planning platform replacing Excel and Anaplan for enterprise FP&A.",
    notable: "Fastest French SaaS to $50M ARR",
  },
];

export const mockTrends: Trend[] = [
  {
    id: "t1",
    title: "Generative AI Embedded in Every SaaS Product",
    signal: "All major SaaS vendors shipping AI copilots; commoditization risk rising",
    direction: "up",
    impact: "High",
    category: "AI",
    industries: ["B2B SaaS", "EdTech"],
    lastUpdated: "2025-04-10",
  },
  {
    id: "t2",
    title: "EU AI Act Implementation Phase",
    signal: "High-risk AI system providers facing compliance deadlines in Q3 2025",
    direction: "up",
    impact: "High",
    category: "Regulation",
    industries: ["AI in Healthcare", "Cybersecurity", "Deep Tech"],
    lastUpdated: "2025-04-08",
  },
  {
    id: "t3",
    title: "Megaround Compression in Climate Tech",
    signal: "Average round size dropped 23% as hardware risks reprice",
    direction: "down",
    impact: "Medium",
    category: "Funding",
    industries: ["European Climate Tech"],
    lastUpdated: "2025-04-05",
  },
  {
    id: "t4",
    title: "Consolidation Wave in French Fintech",
    signal: "M&A activity up 40% YoY as banks acquire digital challengers",
    direction: "up",
    impact: "High",
    category: "Market",
    industries: ["French Fintech"],
    lastUpdated: "2025-04-12",
  },
  {
    id: "t5",
    title: "Federated Learning Becoming Table Stakes in Healthcare AI",
    signal: "Regulatory pressure on data privacy forcing decentralized training adoption",
    direction: "up",
    impact: "Medium",
    category: "AI",
    industries: ["AI in Healthcare"],
    lastUpdated: "2025-04-01",
  },
  {
    id: "t6",
    title: "Micromobility Regulation Tightening Across EU Cities",
    signal: "Paris, Berlin, Amsterdam restricting e-scooter operators to 2–3 per city",
    direction: "down",
    impact: "High",
    category: "Regulation",
    industries: ["Urban Mobility"],
    lastUpdated: "2025-03-28",
  },
  {
    id: "t7",
    title: "Sovereign AI Infrastructure Spend Accelerating",
    signal: "France €109B plan, Germany €20B earmarked for domestic AI compute clusters",
    direction: "up",
    impact: "High",
    category: "Funding",
    industries: ["Deep Tech", "AI in Healthcare"],
    lastUpdated: "2025-04-14",
  },
  {
    id: "t8",
    title: "Cloud Security Spending Outpacing All IT Categories",
    signal: "Gartner: cloud security CAGR 24% through 2027, driven by CISO mandate",
    direction: "up",
    impact: "High",
    category: "Market",
    industries: ["Cybersecurity"],
    lastUpdated: "2025-04-09",
  },
];

export const mockReportData: Record<string, GeneratedReport> = {
  "french-fintech": {
    industry: "French Fintech",
    tagline: "Europe's second-largest fintech hub accelerating through incumbents' transformation",
    overview: {
      market_size: "€45B",
      growth_rate: "+18% YoY",
      maturity: "Growth",
      geography: "France-first, EU-expanding",
      summary:
        "The French fintech ecosystem has emerged as one of Europe's most dynamic, fuelled by strong engineering talent, a proactive regulatory sandbox (ACPR), and pressure on legacy banks to digitize. BNPParibas and Société Générale face margin compression as neo-banks and embedded finance players chip away at core SME banking. The Paris fintech cluster now hosts 900+ active startups and has attracted €2.1B in fresh capital in 2024.",
    },
    trends: [
      { title: "Embedded Finance Expansion", signal: "BaaS APIs enabling non-financial brands to offer financial products", direction: "up", impact: "High" },
      { title: "Open Banking Adoption Surging", signal: "PSD2 enforcement driving account aggregation and payment initiation use cases", direction: "up", impact: "High" },
      { title: "BNPL Regulation Tightening", signal: "Banque de France requiring consumer credit licensing for BNPL providers", direction: "down", impact: "Medium" },
      { title: "Consolidation via M&A", signal: "Traditional banks acquiring fintech players to close capability gaps", direction: "up", impact: "High" },
    ],
    players: [
      { name: "Qonto", type: "Scale-up", stage: "Series C+", hq: "Paris", description: "Business banking for SMEs", founded: 2017, notable: "5M customers, profitable" },
      { name: "Alan", type: "Scale-up", stage: "Series C+", hq: "Paris", description: "Digital health insurance", founded: 2016, notable: "600K members" },
      { name: "Lydia", type: "Scale-up", stage: "Series B", hq: "Paris", description: "P2P payments and neobank", founded: 2013, notable: "8M users across Europe" },
      { name: "Spendesk", type: "Scale-up", stage: "Series C+", hq: "Paris", description: "Spend management platform", founded: 2016, notable: "€10B+ spend managed annually" },
      { name: "PayFit", type: "Scale-up", stage: "Series C+", hq: "Paris", description: "Payroll and HR automation", founded: 2015, notable: "8,000 business customers" },
    ],
    funding: {
      total_2024: "€2.1B",
      top_rounds: [
        { company: "Qonto", amount: "€486M", stage: "Series C+", date: "Jan 2024" },
        { company: "Alan", amount: "€193M", stage: "Series C+", date: "Mar 2024" },
        { company: "Spendesk", amount: "€100M", stage: "Series C+", date: "May 2024" },
        { company: "PayFit", amount: "€90M", stage: "Series C+", date: "Sep 2024" },
      ],
      narrative: "Funding remains resilient despite the broader European downturn, with late-stage rounds dominating as early-stage deal count declined 15%. Institutional co-investment from Tiger Global and Tencent signals international confidence.",
    },
    summary: {
      bullets: [
        "French fintech is entering a consolidation phase with M&A activity up 40% YoY",
        "Embedded finance and BaaS platforms are the fastest-growing sub-segment (+65% YoY)",
        "Regulatory clarity from ACPR positions France favorably vs UK post-Brexit uncertainty",
      ],
      risk: "Rising interest rates eroding neo-bank NIM advantage; legacy banks counter-attacking with digital subsidiaries (BNP Hello Bank, SG Boursorama at 6M customers).",
      opportunity: "SME cross-border payments and embedded payroll for Europe's 25M SMEs remain underserved — €8B TAM with <15% digital penetration.",
      verdict:
        '"French fintech has graduated from disruptor to infrastructure layer. The next 24 months will sort the genuine platform businesses from the feature companies. Bet on distribution moats — those with 1M+ SME relationships will be the acquisition targets."',
    },
  },
  "ai-healthcare": {
    industry: "AI in Healthcare",
    tagline: "Clinical AI transitioning from research proof-of-concept to deployed care pathways",
    overview: {
      market_size: "€28B",
      growth_rate: "+31% YoY",
      maturity: "Early Growth",
      geography: "UK, France, Germany leading",
      summary:
        "European healthcare AI is at an inflection point: regulatory frameworks (EU AI Act, MDR) are creating compliance moats for well-funded players while filtering out weaker competitors. NHS, AP-HP, and Charité partnerships are accelerating real-world evidence generation. Drug discovery AI is attracting the largest rounds, while clinical decision support and medical imaging AI are approaching reimbursement milestones.",
    },
    trends: [
      { title: "Drug Discovery AI Partnerships Scaling", signal: "Big Pharma allocating 15–20% of R&D budget to AI-native CRO partnerships", direction: "up", impact: "High" },
      { title: "Federated Learning Becoming Standard", signal: "GDPR pressure forcing decentralized model training across hospital networks", direction: "up", impact: "High" },
      { title: "MDR Compliance as Competitive Moat", signal: "EU Medical Device Regulation creating 18-month certification bottleneck", direction: "stable", impact: "Medium" },
      { title: "LLM-Powered Clinical Documentation", signal: "Ambient AI scribes reducing physician admin burden by 40%", direction: "up", impact: "High" },
    ],
    players: [
      { name: "Owkin", type: "Scale-up", stage: "Series B", hq: "Paris", description: "Federated learning for drug discovery", founded: 2016, notable: "Sanofi $180M deal" },
      { name: "Nabla", type: "Startup", stage: "Series B", hq: "Paris", description: "AI medical scribe and copilot", founded: 2018, notable: "Used by 30K+ physicians" },
      { name: "Doctolib", type: "Scale-up", stage: "Series C+", hq: "Paris", description: "Healthcare booking + EHR platform", founded: 2013, notable: "60M patients in Europe" },
      { name: "Incepto", type: "Startup", stage: "Series A", hq: "Paris", description: "Radiology AI deployment platform", founded: 2019, notable: "Deployed in 200+ hospitals" },
    ],
    funding: {
      total_2024: "€890M",
      top_rounds: [
        { company: "Doctolib", amount: "€500M", stage: "Series C+", date: "Feb 2024" },
        { company: "Owkin", amount: "€180M", stage: "Series B", date: "Apr 2024" },
        { company: "Nabla", amount: "€45M", stage: "Series B", date: "Jun 2024" },
      ],
      narrative: "Healthcare AI funding is increasingly concentrated in proven revenue-generating platforms. Pure-play diagnostic AI startups face valuation resets unless they demonstrate clinical deployment at scale.",
    },
    summary: {
      bullets: [
        "AI medical scribes are the fastest-growing segment — reducing physician burnout is now a reimbursable outcome",
        "EU AI Act Article 6 classifies most diagnostic AI as high-risk, creating compliance gatekeeping",
        "Hospital system partnerships replacing direct-to-physician go-to-market strategies",
      ],
      risk: "Regulatory approval timelines (CE marking + Notified Body bottleneck) can add 18–24 months to market entry, burning runway for startups.",
      opportunity: "Personalized oncology treatment planning using multi-modal data (genomics + imaging + EHR) — €3.2B addressable in Europe with minimal incumbent competition.",
      verdict:
        '"Healthcare AI is no longer a science project — it is a procurement decision. The companies that have cracked hospital procurement cycles and built reimbursement pathways will compound while others cycle through pilots indefinitely."',
    },
  },
};
